name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deploy
        uses: actions/checkout@v3

      - name: Install and Build 🔧
        run: |
          sudo apt-get install emacs
          emacs -q --script publish.el -f doyougnu/publish
          cp CNAME /build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: deploy # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
